name: flutter_payclip
description: El SDK de Clip es una librería que extiende las capacidades de tu aplicación de punto de venta.
repository: https://github.com/teli-solutions/flutter-payclip
issue_tracker: https://github.com/teli-solutions/flutter-payclip/issues
version: 1.0.3

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.payclip
        pluginClass: FlutterPayclipPlugin
      # ios:
      #   pluginClass: FlutterPayclipPlugin